language: cpp
sudo: false

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    # works on Trusty
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-8
          packages:
            - clang-8
      env:
        - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"

before_install:
  - sudo apt-get update
  # Setup the build environment variables
  - eval "${MATRIX_EVAL}"

script:
    # Build main and tests
    - mkdir build
    - cd build
    - cmake .. 
    - make
    - ./testing



after_success:
    - echo "Success"

after_failure:
    - echo "Something went wrong"