language: cpp

compiler:
    - gcc
    - clang

before_install:
    - test -n $CC  && unset CC
    - test -n $CXX && unset CXX

matrix:
  allow_failures:
    # To allow a build matrix entry to fail, add this key to said entry.
    - custom_allow_failures: true

  include:
    - os: linux
      env:
        - KEY=clang++-7 MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"
    - os: linux
      env:
        - KEY=g++-8 MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

before_install:
    - eval "${MATRIX_EVAL}"


script:
    # Build main and tests
    - mkdir -p build
    - cd build
    - cmake .. 
    - make
    - ./testing
	 

after_success:
    - echo "Success"

after_failure:
    - echo "Something went wrong"