language: cpp
os: linux
dist: xenial

jobs:
  include:
    # works on Precise and Trusty
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

    # works on Trusty
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-10 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-10
            - libstdc++-7-dev
      env:
        - MATRIX_EVAL="CC=clang-10 CXX=clang++-10"

before_install:
  - sudo apt-get update
  # Setup the build environment variables
  - eval "${MATRIX_EVAL}"

script:
    # Build main and tests
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - make
    - ../bin/testing



after_success:
    - echo "Success"

after_failure:
    - echo "Something went wrong"