# Use new trusty images, should yield newer compilers and packages
sudo: required
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env: COMPILER=g++-8
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-8
          packages:
            - clang-8
      env: COMPILER=clang++-8

before_install:
  - sudo apt-get update -qq
- sudo apt-get install -y libopencv-dev

before_install:
    - eval "${MATRIX_EVAL}"

script:
    # Build main and tests
    - mkdir -p build
    - cd build
    - cmake .. 
    - make
    - ./testing


after_success:
    - echo "Success"

after_failure:
    - echo "Something went wrong"